import assert from "node:assert/strict"; import test from "node:test"; import React from "react"; import { renderToStaticMarkup } from "react-dom/server";
import { hasAdminPermission } from "../lib/admin-authorization";
import type { UniversityTuitionManagementApiResponse } from "../lib/university-intelligence/api/tuition-management.client";
import { buildTuitionManagementApiUrl } from "../lib/university-intelligence/api/tuition-management.client";
import { tuitionManagementFilters } from "../app/admin/university-data/universities/[id]/tuition/page";
import TuitionManagementView,{tuitionAmount} from "../app/admin/university-data/universities/[id]/tuition/tuition-management-view";
import { handleAdminUniversityTuitionRequest } from "../app/api/admin/universities/[id]/tuition/route";
const filters={query:"Engineering",studyLevel:"Graduate",degreeLevel:"Masters",programId:"program-1",currency:"USD",period:"credit-hour",academicYear:"2026/27",publicationStatus:"DRAFT" as const,verificationStatus:"DISCOVERED" as const,scope:undefined};
function tuition(overrides:Partial<UniversityTuitionManagementApiResponse["result"]["tuition"][number]>={}):UniversityTuitionManagementApiResponse["result"]["tuition"][number]{return{id:"tuition-immutable-id",programId:null,programName:null,scope:"university-wide",studyLevel:"Undergraduate",degreeLevel:null,amount:25000,minimumAmount:null,maximumAmount:null,currency:"USD",period:"full-program",academicYear:"2026/27",notes:null,publicationStatus:"DRAFT",verificationStatus:"DISCOVERED",updatedAt:"2026-07-25T00:00:00.000Z",...overrides};}
function response(rows=[tuition(),tuition({id:"program-tuition",programId:"program-1",programName:"Engineering",scope:"program-specific",studyLevel:"Graduate",degreeLevel:"Masters",currency:"NPR",period:"credit-hour",publicationStatus:"PUBLISHED",verificationStatus:"OFFICIAL_VERIFIED"})]):UniversityTuitionManagementApiResponse{return{university:{id:"university-id",name:"Example University"},result:{tuition:rows,statistics:{total:2,published:1,draft:1,officiallyVerified:1,universityWide:1,programSpecific:1,undergraduate:1,graduate:1},options:{studyLevels:["Graduate","Undergraduate"],degreeLevels:["Masters"],programs:[{id:"program-1",name:"Engineering"}],currencies:["NPR","USD"],periods:["credit-hour","full-program"],academicYears:["2026/27"]}}};}
const render=(data=response(),active={})=>renderToStaticMarkup(React.createElement(TuitionManagementView,{data,filters:active}));
test("lists draft and published tuition with statistics and distinct scopes",()=>{const html=render();for(const value of ["Total Tuition Records","Published","Draft","Officially Verified","University-wide","Program-specific","Undergraduate","Graduate"])assert.match(html,new RegExp(value));assert.match(html,/is-draft">Draft/);assert.match(html,/is-published">Published/);assert.match(html,/Engineering/);assert.match(html,/Showing 2 of 2 tuition records/);});
test("preserves exact currencies, billing periods, and academic years",()=>{const html=render();assert.match(html,/>USD</);assert.match(html,/>NPR</);assert.match(html,/>full-program</);assert.match(html,/>credit-hour</);assert.match(html,/>2026\/27</);});
test("never presents false zero tuition as an amount",()=>{const shell=tuition({amount:0,minimumAmount:0,maximumAmount:0,currency:null});assert.equal(tuitionAmount(shell),"—");const html=render(response([shell]));assert.match(html,/data-label="Amount" class="tuition-placeholder">—/);assert.doesNotMatch(html,/>0\.00<|>0<|>NaN<|>null<|>undefined</);});
test("renders filters, ignores blanks, and shows helpful empty state",()=>{const html=render(response(),filters);for(const name of ["q","studyLevel","degreeLevel","programId","currency","period","academicYear","publicationStatus","verificationStatus"])assert.match(html,new RegExp(`name="${name}"`));assert.deepEqual(tuitionManagementFilters({q:" Engineering ",studyLevel:"Graduate",degreeLevel:"Masters",programId:"program-1",currency:"USD",period:"credit-hour",academicYear:"2026/27",publicationStatus:"DRAFT",verificationStatus:"DISCOVERED"}),filters);assert.ok(Object.values(tuitionManagementFilters({q:" ",publicationStatus:"INVALID"})).every(value=>value===undefined));const empty=render(response([]));assert.match(empty,/No tuition records found\./);assert.match(empty,/No tuition records have been imported or reviewed for this university yet\./);});
test("uses immutable detail actions and disables public navigation",()=>{const html=render(response([tuition()]));assert.match(html,/href="\/admin\/university-data\/tuition\/tuition-immutable-id">Open Details/);assert.match(html,/aria-disabled="true" title="Public tuition pages are not available">View Public/);assert.doesNotMatch(html,/href="[^"]+">View Public/);});
test("builds protected API requests without a live database",async()=>{const url=buildTuitionManagementApiUrl("https://example.test","university-id",filters);assert.equal(url.pathname,"/api/admin/universities/university-id/tuition");assert.equal(url.searchParams.get("period"),"credit-hour");const service={async listUniversityTuition(){return null;}};assert.equal((await handleAdminUniversityTuitionRequest("missing-id","allowed",{},service)).status,404);assert.equal((await handleAdminUniversityTuitionRequest("university-id","forbidden",{},service)).status,403);assert.equal(hasAdminPermission("SUPER_ADMIN","manage_university_data"),true);assert.equal(hasAdminPermission("EDITOR","manage_university_data"),false);});
