import type { StudentTool } from "./types";

export const studentTools = [
  {
    id: "university-finder",
    slug: "university-finder",
    href: "/student-hub/university-finder",
    title: "University Finder",
    description: "Explore study options that align with your academic profile, interests, and preferred destination.",
    icon: "school",
    status: "launching-first",
    order: 1,
  },
  {
    id: "visa-eligibility-checker",
    slug: "visa-eligibility-checker",
    href: "/student-hub/visa-eligibility-checker",
    title: "Visa Eligibility Checker",
    description: "Review the common readiness factors involved in preparing for a student visa application.",
    icon: "passport",
    status: "coming-soon",
    order: 2,
  },
  {
    id: "cost-calculator",
    slug: "cost-calculator",
    href: "/student-hub/cost-calculator",
    title: "Cost Calculator",
    description: "Plan for tuition, living expenses, travel, and other common study-abroad costs.",
    icon: "calculator",
    status: "coming-soon",
    order: 3,
  },
  {
    id: "scholarship-estimator",
    slug: "scholarship-estimator",
    href: "/student-hub/scholarship-estimator",
    title: "Scholarship Estimator",
    description: "Understand the factors that may influence your scholarship opportunities.",
    icon: "scholarship",
    status: "coming-soon",
    order: 4,
  },
  {
    id: "document-checklist",
    slug: "document-checklist",
    href: "/student-hub/document-checklist",
    title: "Document Checklist",
    description: "Organise the common academic, financial, application, and visa documents you may need.",
    icon: "documents",
    status: "coming-soon",
    order: 5,
  },
] as const satisfies readonly StudentTool[];
