import { auth } from "@/auth";
import { hasAdminPermission } from "@/lib/admin-authorization";
import { TuitionManagementService, TuitionRepository, UniversityRepository, type TuitionManagementFilters, type UniversityPublicationStatus, type UniversityVerificationStatus } from "@/lib/university-intelligence";
export const runtime="nodejs"; export const dynamic="force-dynamic";
type Access="unauthenticated"|"forbidden"|"allowed"; type Service=Pick<TuitionManagementService,"listUniversityTuition">;
const publications:UniversityPublicationStatus[]=["DRAFT","PUBLISHED","ARCHIVED"]; const verifications:UniversityVerificationStatus[]=["DISCOVERED","PARTNER_MATCHED","OFFICIAL_VERIFIED","MANUALLY_VERIFIED","VERIFICATION_FAILED"];
function errorResponse(status:number,code:string,message:string){return Response.json({error:{code,message}},{status,headers:{"Cache-Control":"no-store"}});}
export async function handleAdminUniversityTuitionRequest(idValue:string,access:Access,filters:TuitionManagementFilters,service:Service){if(access==="unauthenticated")return errorResponse(401,"UNAUTHORIZED","Authentication required.");if(access==="forbidden")return errorResponse(403,"FORBIDDEN","Permission denied.");const id=idValue.trim();if(!/^[A-Za-z0-9_-]{1,30}$/.test(id))return errorResponse(404,"NOT_FOUND","University not found.");try{const payload=await service.listUniversityTuition(id,filters);return payload?Response.json(payload,{headers:{"Cache-Control":"private, no-store"}}):errorResponse(404,"NOT_FOUND","University not found.");}catch{console.error("Admin university tuition request failed.");return errorResponse(500,"INTERNAL_ERROR","University tuition could not be loaded.");}}
const service=new TuitionManagementService({universities:new UniversityRepository(),tuition:new TuitionRepository()});
export async function GET(request:Request,context:{params:Promise<{id:string}>}){const session=await auth();const access:Access=!session?.user?"unauthenticated":hasAdminPermission(session.user.role,"manage_university_data")?"allowed":"forbidden";const params=new URL(request.url).searchParams;const publication=params.get("publicationStatus");const verification=params.get("verificationStatus");const scope=params.get("scope");const filters:TuitionManagementFilters={query:params.get("q")?.trim()||undefined,studyLevel:params.get("studyLevel")?.trim()||undefined,degreeLevel:params.get("degreeLevel")?.trim()||undefined,programId:params.get("programId")?.trim()||undefined,currency:params.get("currency")?.trim()||undefined,period:params.get("period")?.trim()||undefined,academicYear:params.get("academicYear")?.trim()||undefined,publicationStatus:publications.includes(publication as UniversityPublicationStatus)?publication as UniversityPublicationStatus:undefined,verificationStatus:verifications.includes(verification as UniversityVerificationStatus)?verification as UniversityVerificationStatus:undefined,scope:scope==="university-wide"||scope==="program-specific"?scope:undefined};return handleAdminUniversityTuitionRequest((await context.params).id,access,filters,service);}
