import type { University } from "./types";

// TODO: Replace this in-repository sample catalog with CMS-managed university
// records after the catalog workflow, validation rules, and editorial ownership
// have been defined. These fictional records must never be presented as real
// admission requirements or institution data.
export const sampleUniversities = [
  {
    id: "sample-university-us-001",
    slug: "sample-northstar-university",
    name: "Sample Northstar University",
    country: "US",
    city: "Sample City",
    logo: null,
    website: "https://example.com/sample-northstar-university",
    studyLevels: ["bachelor", "master"],
    majors: ["Sample Business Program", "Sample Computing Program"],
    minimumGpa: null,
    gpaScale: null,
    englishRequirements: [{ test: "OTHER", minimumOverallScore: null, minimumComponentScore: null, note: "Sample record only; no admission threshold is defined." }],
    tuition: { currency: "USD", minimum: null, maximum: null, period: "year", note: "Sample record only; tuition is not defined." },
    livingCost: { currency: "USD", minimum: null, maximum: null, period: "year", note: "Sample record only; living costs are not defined." },
    applicationFee: { currency: "USD", minimum: null, maximum: null, period: "application", note: "Sample record only; the application fee is not defined." },
    scholarship: { available: false, names: [], maximumAmount: null, note: "Sample record only; scholarship information is not defined." },
    intakePeriods: [{ label: "Sample intake", months: [], note: "Sample record only; intake months are not defined." }],
    stemProgramsAvailable: true,
    featured: true,
    active: true,
    sample: true,
  },
  {
    id: "sample-university-ca-001",
    slug: "sample-maple-coast-college",
    name: "Sample Maple Coast College",
    country: "CA",
    city: "Example Harbour",
    logo: null,
    website: "https://example.com/sample-maple-coast-college",
    studyLevels: ["postgraduate-certificate", "bachelor"],
    majors: ["Sample Design Program", "Sample Project Management Program"],
    minimumGpa: null,
    gpaScale: null,
    englishRequirements: [{ test: "OTHER", minimumOverallScore: null, minimumComponentScore: null, note: "Sample record only; no admission threshold is defined." }],
    tuition: { currency: "CAD", minimum: null, maximum: null, period: "year", note: "Sample record only; tuition is not defined." },
    livingCost: { currency: "CAD", minimum: null, maximum: null, period: "year", note: "Sample record only; living costs are not defined." },
    applicationFee: { currency: "CAD", minimum: null, maximum: null, period: "application", note: "Sample record only; the application fee is not defined." },
    scholarship: { available: false, names: [], maximumAmount: null, note: "Sample record only; scholarship information is not defined." },
    intakePeriods: [{ label: "Sample intake", months: [], note: "Sample record only; intake months are not defined." }],
    featured: false,
    active: true,
    sample: true,
  },
  {
    id: "sample-university-kr-001",
    slug: "sample-hanriver-institute",
    name: "Sample Hanriver Institute",
    country: "KR",
    city: "Example District",
    logo: null,
    website: "https://example.com/sample-hanriver-institute",
    studyLevels: ["bachelor", "master", "doctorate"],
    majors: ["Sample Engineering Program", "Sample International Studies Program"],
    minimumGpa: null,
    gpaScale: null,
    englishRequirements: [{ test: "OTHER", minimumOverallScore: null, minimumComponentScore: null, note: "Sample record only; no admission threshold is defined." }],
    tuition: { currency: "KRW", minimum: null, maximum: null, period: "year", note: "Sample record only; tuition is not defined." },
    livingCost: { currency: "KRW", minimum: null, maximum: null, period: "year", note: "Sample record only; living costs are not defined." },
    applicationFee: { currency: "KRW", minimum: null, maximum: null, period: "application", note: "Sample record only; the application fee is not defined." },
    scholarship: { available: false, names: [], maximumAmount: null, note: "Sample record only; scholarship information is not defined." },
    intakePeriods: [{ label: "Sample intake", months: [], note: "Sample record only; intake months are not defined." }],
    stemProgramsAvailable: true,
    featured: true,
    active: false,
    sample: true,
  },
] as const satisfies readonly University[];
