import { parseUniversityCatalog } from "./schema";
import type { VerificationMetadata } from "./types";

const sampleVerification: VerificationMetadata = {
  verificationStatus: "unverified",
  sourceType: "sample",
  lastReviewedAt: null,
  sourceUrl: null,
  notes: "Fictional demonstration record only.",
};

const unknownScholarship = {
  state: "unknown",
  type: null,
  amount: null,
  currency: null,
  eligibilityNotes: null,
  sourceUrl: null,
  lastReviewedAt: null,
  verification: sampleVerification,
} as const;

export const rawSampleUniversityCatalog = {
  schemaVersion: 1,
  universities: [
  {
    id: "sample-university-us-001",
    slug: "sample-northstar-university",
    name: "Sample Northstar University",
    country: "US",
    city: "Sample City",
    logo: null,
    website: "https://example.com/sample-northstar-university",
    active: true,
    featured: true,
    sampleRecord: true,
    subjectCoverage: "partial",
    verification: sampleVerification,
    programs: [
      {
        id: "sample-program-us-computing-001",
        slug: "sample-computing-program",
        name: "Sample Computing Program",
        subject: "computer-science",
        subjectAliases: ["computing"],
        studyLevel: "bachelor",
        previousQualificationRequirements: [],
        academicRequirements: [],
        englishRequirements: [],
        tuition: null,
        intakes: [],
        scholarship: unknownScholarship,
        locationClassification: "unknown",
        active: true,
        verification: sampleVerification,
      },
      {
        id: "sample-program-us-business-001",
        slug: "sample-business-program",
        name: "Sample Business Program",
        subject: "business-management",
        subjectAliases: ["business"],
        studyLevel: "master",
        previousQualificationRequirements: [],
        academicRequirements: [],
        englishRequirements: [],
        tuition: null,
        intakes: [],
        scholarship: unknownScholarship,
        locationClassification: "unknown",
        active: true,
        verification: sampleVerification,
      },
    ],
  },
  {
    id: "sample-university-ca-001",
    slug: "sample-maple-coast-college",
    name: "Sample Maple Coast College",
    country: "CA",
    city: "Example Harbour",
    logo: null,
    website: "https://example.com/sample-maple-coast-college",
    active: true,
    featured: false,
    sampleRecord: true,
    subjectCoverage: "partial",
    verification: sampleVerification,
    programs: [
      {
        id: "sample-program-ca-design-001",
        slug: "sample-design-program",
        name: "Sample Design Program",
        subject: "arts-design",
        subjectAliases: ["design"],
        studyLevel: "bachelor",
        previousQualificationRequirements: [],
        academicRequirements: [],
        englishRequirements: [],
        tuition: null,
        intakes: [],
        scholarship: unknownScholarship,
        locationClassification: "unknown",
        active: true,
        verification: sampleVerification,
      },
      {
        id: "sample-program-ca-project-001",
        slug: "sample-project-management-program",
        name: "Sample Project Management Program",
        subject: "project-management",
        subjectAliases: [],
        studyLevel: "postgraduate-certificate",
        previousQualificationRequirements: [],
        academicRequirements: [],
        englishRequirements: [],
        tuition: null,
        intakes: [],
        scholarship: unknownScholarship,
        locationClassification: "unknown",
        active: true,
        verification: sampleVerification,
      },
    ],
  },
  {
    id: "sample-university-kr-001",
    slug: "sample-hanriver-institute",
    name: "Sample Hanriver Institute",
    country: "KR",
    city: "Example District",
    logo: null,
    website: "https://example.com/sample-hanriver-institute",
    active: false,
    featured: true,
    sampleRecord: true,
    subjectCoverage: "unknown",
    verification: sampleVerification,
    programs: [
      {
        id: "sample-program-kr-engineering-001",
        slug: "sample-engineering-program",
        name: "Sample Engineering Program",
        subject: "engineering",
        subjectAliases: [],
        studyLevel: "bachelor",
        previousQualificationRequirements: [],
        academicRequirements: [],
        englishRequirements: [],
        tuition: null,
        intakes: [],
        scholarship: unknownScholarship,
        locationClassification: "unknown",
        active: false,
        verification: sampleVerification,
      },
    ],
  },
  ],
} as const;

// This is an explicit migration of the former university-level fictional
// catalog. No unknown admission, tuition, intake, scholarship, GPA, or English
// values are invented during migration.
export const sampleUniversities = parseUniversityCatalog(rawSampleUniversityCatalog.universities);
